const LIBRARY_DATA = [
  {
    "Title": "Sins of the House of Borgia",
    "Author": "Sarah Bower",
    "First_Acquired": "2012-03-28",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Historical Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Extremely Loud and Incredibly Close",
    "Author": "Jonathan Safran Foer",
    "First_Acquired": "2012-03-28",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Dracula",
    "Author": "Bram Stoker",
    "First_Acquired": "2012-03-31",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Horror",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Father Junipero Serra",
    "Author": "Ivy May Bolton",
    "First_Acquired": "2012-04-07",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Biography & Memoir",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Feast of the Goat",
    "Author": "Mario Vargas Llosa",
    "First_Acquired": "2012-04-15",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Fire Monks",
    "Author": "Colleen Morton Busch",
    "First_Acquired": "2012-06-12",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Abraham Lincoln: Vampire Hunter",
    "Author": "Seth Grahame-Smith",
    "First_Acquired": "2012-07-18",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Horror",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Bali: Sekala & Niskala",
    "Author": "Fred B. Eiseman",
    "First_Acquired": "2012-07-18",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Destiny of the Republic",
    "Author": "Candice Millard",
    "First_Acquired": "2012-09-06",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Politics & Geopolitics",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Team of Rivals",
    "Author": "Doris Kearns Goodwin",
    "First_Acquired": "2012-11-09",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Business & Management",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "John Muir Trail",
    "Author": "Elizabeth Wenk",
    "First_Acquired": "2013-02-14",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Mongoliad",
    "Author": "G. Bear; N. Stephenson et al.; Greg Bear; Neal Stephenson; Mark Teppo; Erik Bear; Joseph Brassey; Cooper Moo; Nicole Galland",
    "First_Acquired": "2013-03-31",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Mongoliad (Book 2)",
    "Author": "G. Bear; N. Stephenson et al.",
    "First_Acquired": "2013-03-31",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Forever War",
    "Author": "Joe Haldeman",
    "First_Acquired": "2013-04-03",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "High Lonesome",
    "Author": "Joyce Carol Oates",
    "First_Acquired": "2013-04-13",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Practice of Management",
    "Author": "Peter Drucker; Peter F. Drucker",
    "First_Acquired": "2013-06-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Business & Management",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Nexus",
    "Author": "Ramez Naam; Yuval Noah Harari",
    "First_Acquired": "2013-06-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Gone Girl",
    "Author": "Gillian Flynn",
    "First_Acquired": "2013-09-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On the Nature of Things",
    "Author": "Lucretius; Lucretius; Martin Ferguson Smith",
    "First_Acquired": "2013-10-29",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Buddhism for Busy People",
    "Author": "David Michie",
    "First_Acquired": "2013-11-26",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Junipero Serra",
    "Author": "Steven W. Hackel",
    "First_Acquired": "2013-11-26",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Junípero Serra",
    "Author": "Steven W. Hackel",
    "First_Acquired": "2013-11-26",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Innovator’s Dilemma",
    "Author": "Clayton Christensen",
    "First_Acquired": "2014-01-21",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Innovator's Dilemma",
    "Author": "Clayton M. Christensen",
    "First_Acquired": "2014-01-21",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Everything Store",
    "Author": "Brad Stone",
    "First_Acquired": "2014-03-10",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Hard Thing About Hard Things",
    "Author": "Ben Horowitz",
    "First_Acquired": "2014-03-27",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Living with a Wild God",
    "Author": "Barbara Ehrenreich",
    "First_Acquired": "2014-04-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Annihilation",
    "Author": "Jeff VanderMeer",
    "First_Acquired": "2014-06-01",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Authority",
    "Author": "Jeff VanderMeer",
    "First_Acquired": "2014-06-12",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Green Hills of Africa",
    "Author": "Ernest Hemingway",
    "First_Acquired": "2014-06-17",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Farewell to Arms",
    "Author": "Ernest Hemingway",
    "First_Acquired": "2014-06-17",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A History of the East African Coast",
    "Author": "Charles Cornelius",
    "First_Acquired": "2014-06-17",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Out of Africa",
    "Author": "Isak Dinesen",
    "First_Acquired": "2014-06-30",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Mind and Cosmos",
    "Author": "Thomas Nagel",
    "First_Acquired": "2014-07-22",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Psychology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Capital in the Twenty-First Century",
    "Author": "Thomas Piketty",
    "First_Acquired": "2014-08-03",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Economics",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Acceptance",
    "Author": "Jeff VanderMeer",
    "First_Acquired": "2014-08-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Prague in Danger",
    "Author": "Peter Demetz",
    "First_Acquired": "2014-09-01",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Absolute Recoil",
    "Author": "Slavoj Žižek",
    "First_Acquired": "2014-09-03",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Peripheral",
    "Author": "William Gibson",
    "First_Acquired": "2014-10-29",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Meaning of Human Existence",
    "Author": "Edward O. Wilson",
    "First_Acquired": "2014-10-30",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Philosophy",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Zero History",
    "Author": "William Gibson",
    "First_Acquired": "2015-01-13",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Colorless Tsukuru Tazaki and His Years of Pilgrimage",
    "Author": "Haruki Murakami",
    "First_Acquired": "2015-01-24",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Colorless Tsukuru Tazaki",
    "Author": "Haruki Murakami",
    "First_Acquired": "2015-01-24",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Master and Commander",
    "Author": "Patrick O'Brian; Patrick O’Brian",
    "First_Acquired": "2015-01-24",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Buried Giant",
    "Author": "Kazuo Ishiguro",
    "First_Acquired": "2015-03-04",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The Advantage",
    "Author": "Patrick Lencioni; Patrick M. Lencioni",
    "First_Acquired": "2015-03-04",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Business & Management",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Unconsoled",
    "Author": "Kazuo Ishiguro",
    "First_Acquired": "2015-03-21",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The History of the Decline and Fall of the Roman Empire",
    "Author": "Edward Gibbon",
    "First_Acquired": "2015-03-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "The Decline and Fall of the Roman Empire",
    "Author": "Edward Gibbon",
    "First_Acquired": "2015-03-23",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "The Great Gatsby",
    "Author": "F. Scott Fitzgerald",
    "First_Acquired": "2015-03-29",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "White Noise",
    "Author": "Don DeLillo",
    "First_Acquired": "2015-05-05",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "After Dark",
    "Author": "Haruki Murakami",
    "First_Acquired": "2015-06-09",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Inferno",
    "Author": "Dan Brown",
    "First_Acquired": "2015-07-06",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Seveneves",
    "Author": "Neal Stephenson",
    "First_Acquired": "2015-07-06",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Festival of Insignificance",
    "Author": "Milan Kundera",
    "First_Acquired": "2015-07-12",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Cracking the GRE",
    "Author": "Princeton Review",
    "First_Acquired": "2015-09-09",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Price of Privilege",
    "Author": "Madeline Levine",
    "First_Acquired": "2015-09-09",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Doing School",
    "Author": "Denise Clark Pope",
    "First_Acquired": "2015-09-09",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Wake",
    "Author": "Paul Kingsnorth",
    "First_Acquired": "2015-09-22",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Bone Clocks",
    "Author": "David Mitchell",
    "First_Acquired": "2015-09-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Otherland: City of Golden Shadow",
    "Author": "Tad Williams",
    "First_Acquired": "2015-10-21",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Adventures of Augie March",
    "Author": "Saul Bellow",
    "First_Acquired": "2015-11-14",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Three-Body Problem",
    "Author": "Cixin Liu",
    "First_Acquired": "2015-11-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Dark Forest",
    "Author": "Cixin Liu",
    "First_Acquired": "2015-12-10",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Infinite Jest",
    "Author": "David Foster Wallace",
    "First_Acquired": "2015-12-27",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Season of the Witch",
    "Author": "David Talbot",
    "First_Acquired": "2016-01-04",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Stone Reader",
    "Author": "Peter Catapano; Simon Critchley",
    "First_Acquired": "2016-02-10",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Book of Laughter and Forgetting",
    "Author": "Milan Kundera",
    "First_Acquired": "2016-03-26",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Question of Upbringing",
    "Author": "Anthony Powell",
    "First_Acquired": "2016-03-27",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Family Life",
    "Author": "Akhil Sharma",
    "First_Acquired": "2016-04-19",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Satin Island",
    "Author": "Tom McCarthy",
    "First_Acquired": "2016-04-27",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Spectator Bird",
    "Author": "Wallace Stegner",
    "First_Acquired": "2016-05-02",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Goldfinch",
    "Author": "Donna Tartt",
    "First_Acquired": "2016-05-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Big Picture",
    "Author": "Sean Carroll; Sean M. Carroll",
    "First_Acquired": "2016-06-12",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Religion for Atheists",
    "Author": "Alain de Botton",
    "First_Acquired": "2016-06-24",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The News",
    "Author": "Alain de Botton",
    "First_Acquired": "2016-06-24",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Man in the High Castle",
    "Author": "Philip K. Dick",
    "First_Acquired": "2016-07-17",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Death’s End",
    "Author": "Cixin Liu",
    "First_Acquired": "2016-07-20",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Passage",
    "Author": "Justin Cronin",
    "First_Acquired": "2016-07-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Angle of Repose",
    "Author": "Wallace Stegner",
    "First_Acquired": "2016-07-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Twelve",
    "Author": "Justin Cronin",
    "First_Acquired": "2016-08-16",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "What Got You Here Won't Get You There",
    "Author": "Marshall Goldsmith; Mark Reiter",
    "First_Acquired": "2016-08-16",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "What Got You Here Won’t Get You There",
    "Author": "Marshall Goldsmith",
    "First_Acquired": "2016-08-16",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Order of Things",
    "Author": "Michel Foucault",
    "First_Acquired": "2016-08-16",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Death's End",
    "Author": "Cixin Liu",
    "First_Acquired": "2016-09-19",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Introducing NLP",
    "Author": "Joseph O’Connor; John Seymour",
    "First_Acquired": "2016-10-11",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Structure of Magic Vol 1",
    "Author": "Richard Bandler; John Grinder",
    "First_Acquired": "2016-10-24",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Fantasy",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Co-Active Coaching",
    "Author": "Henry Kimsey-House; Karen Kimsey-House; Phillip Sandahl; Laura Whitworth; Kimsey-House et al.",
    "First_Acquired": "2016-10-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Supposedly Fun Thing I'll Never Do Again",
    "Author": "David Foster Wallace",
    "First_Acquired": "2016-11-11",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Shantaram",
    "Author": "Gregory David Roberts",
    "First_Acquired": "2016-11-28",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On What Matters",
    "Author": "Derek Parfit",
    "First_Acquired": "2017-01-03",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On What Matters (Vol 1)",
    "Author": "Derek Parfit",
    "First_Acquired": "2017-01-03",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On Art and Mindfulness",
    "Author": "Matthew Fox",
    "First_Acquired": "2017-01-20",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Psychology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Imperium",
    "Author": "Robert Harris",
    "First_Acquired": "2017-01-27",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Hillbilly Elegy",
    "Author": "J. D. Vance; J.D. Vance",
    "First_Acquired": "2017-03-31",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Genius Decision",
    "Author": "Hunter M. Adams",
    "First_Acquired": "2017-04-06",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The E-Myth Revisited",
    "Author": "Michael Gerber",
    "First_Acquired": "2017-07-13",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Leading Change",
    "Author": "John Kotter; John P. Kotter",
    "First_Acquired": "2017-07-13",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Time Travel",
    "Author": "James Gleick",
    "First_Acquired": "2017-09-12",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Science Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The Open Society and its Enemies (Vol 1)",
    "Author": "Karl Popper",
    "First_Acquired": "2017-09-12",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Sociology & Anthropology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "HBR 10 Must Reads on Change Management",
    "Author": "Various",
    "First_Acquired": "2017-10-13",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Business & Management",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Sapiens",
    "Author": "Yuval Noah Harari",
    "First_Acquired": "2017-10-17",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "American War",
    "Author": "Omar El Akkad",
    "First_Acquired": "2017-11-24",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Hacienda Style",
    "Author": "Karen Witynski",
    "First_Acquired": "2017-11-28",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Principles: Life and Work",
    "Author": "Ray Dalio",
    "First_Acquired": "2017-12-19",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Let My People Go Surfing",
    "Author": "Yvon Chouinard",
    "First_Acquired": "2017-12-22",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Connected Company",
    "Author": "Dave Gray; Thomas Vander Wal",
    "First_Acquired": "2017-12-26",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Business & Management",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Homo Deus",
    "Author": "Yuval Noah Harari",
    "First_Acquired": "2018-02-14",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "The Order of Time",
    "Author": "Carlo Rovelli",
    "First_Acquired": "2018-06-25",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Measure What Matters",
    "Author": "John Doerr",
    "First_Acquired": "2018-07-02",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Historical Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "An Officer and a Spy",
    "Author": "Robert Harris",
    "First_Acquired": "2018-07-31",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Mystery / Thriller",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Fatherland",
    "Author": "Robert Harris",
    "First_Acquired": "2018-08-02",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Munich",
    "Author": "Robert Harris",
    "First_Acquired": "2018-08-02",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Down to Earth",
    "Author": "Bruno Latour",
    "First_Acquired": "2018-10-25",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Reality Is Not What It Seems",
    "Author": "Carlo Rovelli",
    "First_Acquired": "2018-11-02",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Lime Works",
    "Author": "Thomas Bernhard",
    "First_Acquired": "2018-11-07",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Brave New World",
    "Author": "Aldous Huxley",
    "First_Acquired": "2018-11-10",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Who: The A Method for Hiring",
    "Author": "Geoff Smart; Randy Street",
    "First_Acquired": "2018-11-15",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Neighborhood",
    "Author": "Luis Alberto Urrea",
    "First_Acquired": "2018-11-20",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Jungle Grows Back",
    "Author": "Robert Kagan",
    "First_Acquired": "2018-11-27",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "How to Change Your Mind",
    "Author": "Michael Pollan",
    "First_Acquired": "2018-11-30",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Self-Help / Productivity",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Border Districts",
    "Author": "Gerald Murnane",
    "First_Acquired": "2018-12-21",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Never Split the Difference",
    "Author": "Chris Voss",
    "First_Acquired": "2019-01-01",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Ball Lightning",
    "Author": "Cixin Liu",
    "First_Acquired": "2019-01-08",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Gallic Wars",
    "Author": "Julius Caesar",
    "First_Acquired": "2019-01-17",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Bad Blood",
    "Author": "John Carreyrou",
    "First_Acquired": "2019-02-04",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "An End to Upside Down Thinking",
    "Author": "Mark Gober",
    "First_Acquired": "2019-02-04",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Psychology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Kingfisher Secret",
    "Author": "Anonymous",
    "First_Acquired": "2019-02-06",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Mystery / Thriller",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "A Wizard of Earthsea",
    "Author": "Ursula K. Le Guin",
    "First_Acquired": "2019-02-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Fantasy",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "All Systems Red",
    "Author": "Martha Wells",
    "First_Acquired": "2019-02-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Tombs of Atuan",
    "Author": "Ursula K. Le Guin",
    "First_Acquired": "2019-02-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Farthest Shore",
    "Author": "Ursula K. Le Guin",
    "First_Acquired": "2019-03-03",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Uninhabitable Earth",
    "Author": "David Wallace-Wells",
    "First_Acquired": "2019-03-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Psychology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Sovereign Individual",
    "Author": "James Dale Davidson; William Rees-Mogg",
    "First_Acquired": "2019-03-22",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Lessons of History",
    "Author": "Will Durant; Ariel Durant",
    "First_Acquired": "2019-04-01",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Alexander the Great",
    "Author": "Philip Freeman",
    "First_Acquired": "2019-04-18",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Portrait of the Artist as a Young Man",
    "Author": "James Joyce",
    "First_Acquired": "2019-05-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Trillion Dollar Coach",
    "Author": "Eric Schmidt; Jonathan Rosenberg; Alan Eagle",
    "First_Acquired": "2019-05-22",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Product-Led Growth",
    "Author": "Wes Bush",
    "First_Acquired": "2019-06-02",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Post Captain",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-07-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Conscious",
    "Author": "Annaka Harris",
    "First_Acquired": "2019-07-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Avogadro Corp",
    "Author": "William Hertling",
    "First_Acquired": "2019-09-04",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Testaments",
    "Author": "Margaret Atwood",
    "First_Acquired": "2019-09-18",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "H.M.S. Surprise",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-10-14",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Mauritius Command",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-10-30",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Desolation Island",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-11-11",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Fortune of War",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-11-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Superintelligence",
    "Author": "Nick Bostrom",
    "First_Acquired": "2019-11-21",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Reasons and Persons",
    "Author": "Derek Parfit",
    "First_Acquired": "2019-11-21",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Surgeon’s Mate",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-12-02",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Ionian Mission",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-12-10",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Treason’s Harbour",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2019-12-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Far Side of the World",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-01-06",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Reverse of the Medal",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-01-15",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Sacre Bleu",
    "Author": "Christopher Moore",
    "First_Acquired": "2020-01-18",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Letter of Marque",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-01-22",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Thirteen-Gun Salute",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-01-28",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Nutmeg of Consolation",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-02-04",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Truelove",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-02-10",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Wine-Dark Sea",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-02-23",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Leviathan Wakes",
    "Author": "James S.A. Corey",
    "First_Acquired": "2020-02-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Commodore",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-03-02",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Yellow Admiral",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-03-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Hundred Days",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2020-04-15",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Burr",
    "Author": "Gore Vidal",
    "First_Acquired": "2020-06-12",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Beloved",
    "Author": "Toni Morrison",
    "First_Acquired": "2020-06-14",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Snow",
    "Author": "John Banville",
    "First_Acquired": "2020-10-07",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Wolf Hall",
    "Author": "Hilary Mantel",
    "First_Acquired": "2020-11-20",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Leaving the Atocha Station",
    "Author": "Ben Lerner",
    "First_Acquired": "2020-11-21",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Post Corona",
    "Author": "Scott Galloway",
    "First_Acquired": "2020-12-04",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Woman of No Importance",
    "Author": "Sonia Purnell",
    "First_Acquired": "2020-12-17",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Mortal Questions",
    "Author": "Thomas Nagel",
    "First_Acquired": "2020-12-22",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Bring Up the Bodies",
    "Author": "Hilary Mantel",
    "First_Acquired": "2020-12-26",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Caliban’s War",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-01-05",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Forty Signs of Rain",
    "Author": "Kim Stanley Robinson",
    "First_Acquired": "2021-01-25",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Abaddon’s Gate",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-01-25",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On Having No Head",
    "Author": "Douglas Harding",
    "First_Acquired": "2021-01-27",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Cibola Burn",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-02-09",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Nemesis Games",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-02-21",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Sympathizer",
    "Author": "Viet Thanh Nguyen",
    "First_Acquired": "2021-02-28",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Klara and the Sun",
    "Author": "Kazuo Ishiguro",
    "First_Acquired": "2021-03-01",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The Mirror & the Light",
    "Author": "Hilary Mantel",
    "First_Acquired": "2021-03-05",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Tiamat’s Wrath",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-03-08",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Persepolis Rising",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-03-08",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Babylon’s Ashes",
    "Author": "James S.A. Corey",
    "First_Acquired": "2021-03-08",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Left Hand of Darkness",
    "Author": "Ursula K. Le Guin",
    "First_Acquired": "2021-04-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Dispossessed",
    "Author": "Ursula K. Le Guin",
    "First_Acquired": "2021-04-24",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "2034",
    "Author": "Elliot Ackerman; James Stavridis",
    "First_Acquired": "2021-04-28",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "12 Rules for Life",
    "Author": "Jordan B. Peterson",
    "First_Acquired": "2021-05-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "How Democracies Die",
    "Author": "Steven Levitsky; Daniel Ziblatt",
    "First_Acquired": "2021-06-01",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Overstory",
    "Author": "Richard Powers",
    "First_Acquired": "2021-06-06",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "21 Lessons for the 21st Century",
    "Author": "Yuval Noah Harari",
    "First_Acquired": "2021-06-23",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "This Is Your Mind on Plants",
    "Author": "Michael Pollan",
    "First_Acquired": "2021-07-11",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Psychology",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Children of Time",
    "Author": "Adrian Tchaikovsky",
    "First_Acquired": "2021-07-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Consolations",
    "Author": "David Whyte",
    "First_Acquired": "2021-07-30",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Freedom",
    "Author": "Jonathan Franzen",
    "First_Acquired": "2021-08-22",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Blue at the Mizzen",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2021-09-03",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Big White Ghetto",
    "Author": "Kevin D. Williamson; Kevin Williamson",
    "First_Acquired": "2021-09-10",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Foundation",
    "Author": "Isaac Asimov",
    "First_Acquired": "2021-09-24",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Foundation and Empire",
    "Author": "Isaac Asimov",
    "First_Acquired": "2021-09-30",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Second Foundation",
    "Author": "Isaac Asimov",
    "First_Acquired": "2021-10-09",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Dune",
    "Author": "Frank Herbert",
    "First_Acquired": "2021-11-15",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Dune Messiah",
    "Author": "Frank Herbert",
    "First_Acquired": "2021-11-19",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Sweet Spot",
    "Author": "Paul Bloom",
    "First_Acquired": "2021-11-23",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Principles for Dealing with the Changing World Order",
    "Author": "Ray Dalio",
    "First_Acquired": "2021-12-01",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Ministry for the Future",
    "Author": "Kim Stanley Robinson",
    "First_Acquired": "2021-12-24",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Virtual Light",
    "Author": "William Gibson",
    "First_Acquired": "2022-01-04",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Total Freedom: The Essential Krishnamurti",
    "Author": "J. Krishnamurti",
    "First_Acquired": "2022-01-11",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "J Krishnamurti Commentaries On Living Series 2",
    "Author": "J Krishnamurti; J. Krishnamurti",
    "First_Acquired": "2022-01-11",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Termination Shock",
    "Author": "Neal Stephenson",
    "First_Acquired": "2022-01-12",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Zone to Win",
    "Author": "Geoffrey A. Moore",
    "First_Acquired": "2022-01-27",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Shards of Earth",
    "Author": "Adrian Tchaikovsky",
    "First_Acquired": "2022-02-07",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The First Man in Rome",
    "Author": "Colleen McCullough",
    "First_Acquired": "2022-02-17",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Pillars of the Earth",
    "Author": "Ken Follett",
    "First_Acquired": "2022-03-18",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Shogun",
    "Author": "James Clavell",
    "First_Acquired": "2022-04-21",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "World Without End",
    "Author": "Ken Follett",
    "First_Acquired": "2022-04-21",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Tai-Pan",
    "Author": "James Clavell",
    "First_Acquired": "2022-05-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Gai-Jin",
    "Author": "James Clavell",
    "First_Acquired": "2022-06-05",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Golf My Way",
    "Author": "Jack Nicklaus",
    "First_Acquired": "2022-07-14",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The High Sierra",
    "Author": "Kim Stanley Robinson",
    "First_Acquired": "2022-07-22",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The High Sierra: A Love Story",
    "Author": "Kim Stanley Robinson",
    "First_Acquired": "2022-07-28",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Back Country",
    "Author": "Gary Snyder",
    "First_Acquired": "2022-07-28",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Gates of Athens",
    "Author": "Conn Iggulden",
    "First_Acquired": "2022-09-12",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "How the World Really Works",
    "Author": "Vaclav Smil",
    "First_Acquired": "2022-09-12",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Column of Fire",
    "Author": "Ken Follett",
    "First_Acquired": "2022-10-06",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Passenger",
    "Author": "Cormac McCarthy",
    "First_Acquired": "2022-10-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Stella Maris",
    "Author": "Cormac McCarthy",
    "First_Acquired": "2022-12-06",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Fully Automated Luxury Communism",
    "Author": "Aaron Bastani",
    "First_Acquired": "2022-12-23",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Long Con: A Novel",
    "Author": "Michael Gruber",
    "First_Acquired": "2023-01-23",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Long Con",
    "Author": "Michael Gruber",
    "First_Acquired": "2023-01-23",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Fundamentals",
    "Author": "Frank Wilczek",
    "First_Acquired": "2023-01-27",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "All the Pretty Horses",
    "Author": "Cormac McCarthy",
    "First_Acquired": "2023-02-01",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Passenger Box Set",
    "Author": "Cormac McCarthy",
    "First_Acquired": "2023-02-03",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Gerhard Richter: Painting After the Subject of History",
    "Author": "David Anfam",
    "First_Acquired": "2023-02-07",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Leviathan Falls",
    "Author": "James S.A. Corey",
    "First_Acquired": "2023-02-09",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Creative Act",
    "Author": "Rick Rubin",
    "First_Acquired": "2023-02-15",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Remains of the Day",
    "Author": "Kazuo Ishiguro",
    "First_Acquired": "2023-03-29",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The Unknown Shore",
    "Author": "Patrick O’Brian",
    "First_Acquired": "2023-04-13",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Wager",
    "Author": "David Grann",
    "First_Acquired": "2023-04-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Nothing Like It in the World",
    "Author": "Stephen E. Ambrose",
    "First_Acquired": "2023-05-18",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Zero-Sum: Stories",
    "Author": "Joyce Carol Oates",
    "First_Acquired": "2023-07-17",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "A Man in Love",
    "Author": "Karl Ove Knausgaard",
    "First_Acquired": "2023-07-28",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Pax",
    "Author": "Tom Holland",
    "First_Acquired": "2023-09-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Rubicon",
    "Author": "Tom Holland",
    "First_Acquired": "2023-10-31",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Alchemist",
    "Author": "Paulo Coelho",
    "First_Acquired": "2023-11-10",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "Gilead",
    "Author": "Marilynne Robinson",
    "First_Acquired": "2023-11-29",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Oryx and Crake",
    "Author": "Margaret Atwood",
    "First_Acquired": "2023-12-24",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "The Year of the Flood",
    "Author": "Margaret Atwood",
    "First_Acquired": "2024-01-02",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Literary Fiction",
    "Fiction_Nonfiction": "Fiction",
    "Difficulty": "Light"
  },
  {
    "Title": "You Dreamed of Empires",
    "Author": "Álvaro Enrigue",
    "First_Acquired": "2024-01-12",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Palo Alto: A History of California Capitalism ",
    "Author": "Malcolm Harris",
    "First_Acquired": "2024-01-16",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": "checked",
    "Has_Physical": NaN,
    "Primary_Genre": "History",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "HBR's 10 Must Reads on AI",
    "Author": "Various",
    "First_Acquired": "2024-01-16",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Palo Alto",
    "Author": "Malcolm Harris",
    "First_Acquired": "2024-01-16",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Free Agents",
    "Author": "Kevin J. Mitchell",
    "First_Acquired": "2024-02-14",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Fall; or Dodge in Hell",
    "Author": "Neal Stephenson",
    "First_Acquired": "2024-02-27",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Determined",
    "Author": "Robert M. Sapolsky",
    "First_Acquired": "2024-03-23",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Consider Phlebas",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-04-04",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Player of Games",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-04-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Use of Weapons",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-05-28",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The State of the Art",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-06-29",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Corrections",
    "Author": "Jonathan Franzen",
    "First_Acquired": "2024-07-12",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Pattern Breakers: Why Some Start-Ups Change the Future",
    "Author": "Jeffrey Funk",
    "First_Acquired": "2024-08-08",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Matter",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-08-27",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "In Ascension",
    "Author": "Martin MacInnes",
    "First_Acquired": "2024-09-03",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Vegetarian",
    "Author": "Han Kang",
    "First_Acquired": "2024-10-11",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Ministry of Time",
    "Author": "Kaliane Bradley",
    "First_Acquired": "2024-10-31",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "On Trails",
    "Author": "Robert Moor",
    "First_Acquired": "2024-11-01",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Braiding Sweetgrass",
    "Author": "Robin Wall Kimmerer",
    "First_Acquired": "2024-11-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Power Law",
    "Author": "Sebastian Mallaby",
    "First_Acquired": "2024-11-26",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Stories of Your Life and Others",
    "Author": "Ted Chiang",
    "First_Acquired": "2024-12-17",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Hydrogen Sonata",
    "Author": "Iain M. Banks",
    "First_Acquired": "2024-12-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Anxious Generation",
    "Author": "Jonathan Haidt",
    "First_Acquired": "2025-01-13",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The City and Its Uncertain Walls",
    "Author": "Haruki Murakami",
    "First_Acquired": "2025-02-14",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Democracy in America",
    "Author": "Alexis de Tocqueville; Harvey Mansfield (trans.)",
    "First_Acquired": "2025-04-25",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "Politics & Geopolitics",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Dense"
  },
  {
    "Title": "Eyes of the Void",
    "Author": "Adrian Tchaikovsky",
    "First_Acquired": "2025-04-26",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "AI Engineering",
    "Author": "Chip Huyen",
    "First_Acquired": "2025-05-20",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Until the End of Time",
    "Author": "Brian Greene",
    "First_Acquired": "2025-05-20",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Untethered Soul",
    "Author": "Michael A. Singer",
    "First_Acquired": "2025-05-30",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Four Thousand Weeks",
    "Author": "Oliver Burkeman",
    "First_Acquired": "2025-05-30",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Meditations",
    "Author": "Marcus Aurelius; Gregory Hays (trans.)",
    "First_Acquired": "2025-06-13",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Build",
    "Author": "Tony Fadell",
    "First_Acquired": "2025-06-20",
    "Read_Status": "Read",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Abundance",
    "Author": "Ezra Klein; Derek Thompson",
    "First_Acquired": "2025-07-01",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Surface Detail",
    "Author": "Iain M. Banks",
    "First_Acquired": "2025-08-03",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "Vera or Faith",
    "Author": "Gary Shteyngart",
    "First_Acquired": "2025-09-02",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "Religion & Spirituality",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Terminal List",
    "Author": "Jack Carr",
    "First_Acquired": "2025-10-27",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "The Emergency",
    "Author": "George Packer",
    "First_Acquired": "2025-11-19",
    "Read_Status": "Read",
    "Has_Audible": "checked",
    "Has_Kindle": NaN,
    "Has_Physical": NaN,
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  },
  {
    "Title": "When Montezuma Met Cortés",
    "Author": "Matthew Restall",
    "First_Acquired": "2025-11-19",
    "Read_Status": "Unread",
    "Has_Audible": NaN,
    "Has_Kindle": NaN,
    "Has_Physical": "checked",
    "Primary_Genre": "General Nonfiction",
    "Fiction_Nonfiction": "Nonfiction",
    "Difficulty": "Moderate"
  }
];